# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='guest', max_length=30),
        ),
    ]
